// Generated by generate_runnable_testcase.py on 2021-08-24 13:49:33.522659
// Trace file: trace_0_81007.inv_2

#include "test_cluster.h"

// Note:
//   Server id starts from 0, i.e. S0's id is 0
//   Msg seq starts from 1

// Abbreviation:
//   rc_: Raft Controller
//   RV:  Request Vote msg
//   RVR: Request Vote Response msg
//   AE:  Append Entries msg
//   AER: Append Entries Response msg
//   SS:  SnapShot msg

void TestCluster_trace_0_81007_inv_2_committed_log_replicated_majority(CuTest * tc) {
    info( 1, "Init 3 servers                         "); rc_init_cluster(3, tc);
    info( 2, "Network partition add S0               "); add_to_network_partition(0);
    info( 3, "S1 becomes candidate                   "); rc_election_timeout(1);
    info( 4, "Network not add unreachable RV S1 -> S0");  
    info( 5, "S1 sends RV 1 to S2                    "); assert_msg_seq_type(1, MSG_REQUESTVOTE);
    info( 6, "S2 receives RV 1 from S1               "); rc_deliver(1, MSG_REQUESTVOTE);
    info( 6, "S2 sends RVR 2 to S1                   "); assert_msg_seq_type(2, MSG_REQUESTVOTE_RESPONSE);
    info( 7, "S1 receives RVR 2 from S2              "); rc_deliver(2, MSG_REQUESTVOTE_RESPONSE);
    info( 8, "Network not add unreachable AE S1 -> S0");  
    info( 9, "S1 sends AE 3 to S2                    "); assert_msg_seq_type(3, MSG_APPENDENTRIES);
    info(10, "Client appends CMD2 to S1              "); rc_client_operation(1, CMD2);
    info(11, "Network not add unreachable AE S1 -> S0");  
    info(12, "S1 sends AE 4 to S2                    "); assert_msg_seq_type(4, MSG_APPENDENTRIES);
    info(13, "S1 sends heartbeat                     "); rc_request_timeout(1);
    info(14, "Network not add unreachable AE S1 -> S0");  
    info(15, "S1 sends AE 5 to S2                    "); assert_msg_seq_type(5, MSG_APPENDENTRIES);
    info(16, "Client appends CMD2 to S1              "); rc_client_operation(1, CMD2);
    info(17, "S1 sends heartbeat                     "); rc_request_timeout(1);
    info(18, "Network not add unreachable AE S1 -> S0");  
    info(19, "S1 sends AE 6 to S2                    "); assert_msg_seq_type(6, MSG_APPENDENTRIES);
    info(20, "Network drop seq 3                     "); drop_msg(3);
    info(21, "S2 receives AE 4 from S1               "); rc_deliver(4, MSG_APPENDENTRIES);
    info(21, "S2 sends AER 7 to S1                   "); assert_msg_seq_type(7, MSG_APPENDENTRIES_RESPONSE);
    info(22, "S1 receives AER 7 from S2              "); rc_deliver(7, MSG_APPENDENTRIES_RESPONSE);
    info(22, "S1 sends AE|SS 8 to S2                 "); assert_msg_seq_type(8, MSG_APPENDENTRIES | MSG_SNAPSHOT);
    info(23, "Network drop seq 6                     "); drop_msg(6);
    info(24, "S2 receives unordered AE 8 from S1     "); rc_deliver(8, MSG_APPENDENTRIES);
    info(24, "S2 sends AER 9 to S1                   "); assert_msg_seq_type(9, MSG_APPENDENTRIES_RESPONSE);
    info(25, "Client appends CMD1 to S1              "); rc_client_operation(1, CMD1);
    info(26, "S1 receives AER 9 from S2              "); rc_deliver(9, MSG_APPENDENTRIES_RESPONSE);
    info(26, "S1 sends AE|SS 10 to S2                "); assert_msg_seq_type(10, MSG_APPENDENTRIES | MSG_SNAPSHOT);
    info(27, "Network duplicate seq 10 -> 11         "); dup_msg(10);
    info(28, "Client appends CMD2 to S1              "); rc_client_operation(1, CMD2);
    info(29, "S1 executes snapshot                   "); rc_exec_snapshot(1);
    info(30, "Network not add unreachable SS S1 -> S0");  
    info(31, "Network partition recovered            "); clear_network_partition();
    info(32, "S2 executes snapshot                   "); rc_exec_snapshot(2);
    info(33, "Network duplicate seq 5 -> 12          "); dup_msg(5);
    info(34, "S2 receives AE 5 from S1               "); rc_deliver(5, MSG_APPENDENTRIES);
    info(34, "S2 sends AER 13 to S1                  "); assert_msg_seq_type(13, MSG_APPENDENTRIES_RESPONSE);
    info(35, "S2 receives unordered AE 11 from S1    "); rc_deliver(11, MSG_APPENDENTRIES);
    info(35, "S2 sends AER 14 to S1                  "); assert_msg_seq_type(14, MSG_APPENDENTRIES_RESPONSE);
    info(36, "S1 receives unordered AER 14 from S2   "); rc_deliver(14, MSG_APPENDENTRIES_RESPONSE);
    info(36, "S1 sends AE|SS 15 to S2                "); assert_msg_seq_type(15, MSG_APPENDENTRIES | MSG_SNAPSHOT);

    info(36, "Guess committed logs replicated to how many servers?");
    assert_inv2();
}

void TestCluster_trace_4_63114_inv_3_committed_log_is_durable(CuTest * tc) {
    info( 1, "Init 3 servers                         "); rc_init_cluster(3, tc);
    info( 2, "S0 becomes candidate                   "); rc_election_timeout(0);
    info( 3, "S0 sends RV 1 to S1                    "); assert_msg_seq_type(1, MSG_REQUESTVOTE);
    info( 4, "S0 sends RV 2 to S2                    "); assert_msg_seq_type(2, MSG_REQUESTVOTE);
    info( 5, "S1 receives RV 1 from S0               "); rc_deliver(1, MSG_REQUESTVOTE);
    info( 5, "S1 sends RVR 3 to S0                   "); assert_msg_seq_type(3, MSG_REQUESTVOTE_RESPONSE);
    info( 6, "S2 becomes candidate                   "); rc_election_timeout(2);
    info( 7, "S2 sends RV 4 to S0                    "); assert_msg_seq_type(4, MSG_REQUESTVOTE);
    info( 8, "S2 sends RV 5 to S1                    "); assert_msg_seq_type(5, MSG_REQUESTVOTE);
    info( 9, "Network drop seq 4                     "); drop_msg(4);
    info(10, "Network drop seq 2                     "); drop_msg(2);
    info(11, "Network duplicate seq 3 -> 6           "); dup_msg(3);
    info(12, "S2 becomes candidate                   "); rc_election_timeout(2);
    info(13, "S2 sends RV 7 to S0                    "); assert_msg_seq_type(7, MSG_REQUESTVOTE);
    info(14, "S2 sends RV 8 to S1                    "); assert_msg_seq_type(8, MSG_REQUESTVOTE);
    info(15, "S1 receives RV 5 from S2               "); rc_deliver(5, MSG_REQUESTVOTE);
    info(15, "S1 sends RVR 9 to S2                   "); assert_msg_seq_type(9, MSG_REQUESTVOTE_RESPONSE);
    info(16, "Network partition add S0               "); add_to_network_partition(0);
    info(17, "S0 receives RVR 3 from S1              "); rc_deliver(3, MSG_REQUESTVOTE_RESPONSE);
    info(18, "Network not add unreachable AE S0 -> S1");  
    info(19, "Network not add unreachable AE S0 -> S2");  
    info(20, "Network not dup unreachable seq 7      ");  
    info(21, "Client appends CMD1 to S0              "); rc_client_operation(0, CMD1);
    info(22, "Network not add unreachable AE S0 -> S1");  
    info(23, "Network not add unreachable AE S0 -> S2");  
    info(24, "Network partition recovered            "); clear_network_partition();
    info(25, "S1 receives RV 8 from S2               "); rc_deliver(8, MSG_REQUESTVOTE);
    info(25, "S1 sends RVR 10 to S2                  "); assert_msg_seq_type(10, MSG_REQUESTVOTE_RESPONSE);
    info(26, "S2 receives unordered RVR 10 from S1   "); rc_deliver(10, MSG_REQUESTVOTE_RESPONSE);
    info(27, "S2 sends AE 11 to S0                   "); assert_msg_seq_type(11, MSG_APPENDENTRIES);
    info(28, "S2 sends AE 12 to S1                   "); assert_msg_seq_type(12, MSG_APPENDENTRIES);
    info(29, "S1 receives AE 12 from S2              "); rc_deliver(12, MSG_APPENDENTRIES);
    info(29, "S1 sends AER 13 to S2                  "); assert_msg_seq_type(13, MSG_APPENDENTRIES_RESPONSE);
    info(30, "S0 receives unordered AE 11 from S2    "); rc_deliver(11, MSG_APPENDENTRIES);
    info(30, "S0 sends AER 14 to S2                  "); assert_msg_seq_type(14, MSG_APPENDENTRIES_RESPONSE);
    info(31, "S0 receives unordered RV 7 from S2     "); rc_deliver(7, MSG_REQUESTVOTE);
    info(31, "S0 sends RVR 15 to S2                  "); assert_msg_seq_type(15, MSG_REQUESTVOTE_RESPONSE);
    info(32, "S2 receives RVR 9 from S1              "); rc_deliver(9, MSG_REQUESTVOTE_RESPONSE);
    info(33, "S2 receives AER 13 from S1             "); rc_deliver(13, MSG_APPENDENTRIES_RESPONSE);
    info(34, "S2 receives AER 14 from S0             "); rc_deliver(14, MSG_APPENDENTRIES_RESPONSE);
    info(35, "Client appends CMD1 to S2              "); rc_client_operation(2, CMD1);
    info(36, "S2 sends AE 16 to S0                   "); assert_msg_seq_type(16, MSG_APPENDENTRIES);
    info(37, "S2 sends AE 17 to S1                   "); assert_msg_seq_type(17, MSG_APPENDENTRIES);
    info(38, "S2 receives RVR 15 from S0             "); rc_deliver(15, MSG_REQUESTVOTE_RESPONSE);
    info(39, "Client appends CMD2 to S2              "); rc_client_operation(2, CMD2);
    info(40, "S1 receives AE 17 from S2              "); rc_deliver(17, MSG_APPENDENTRIES);
    info(40, "S1 sends AER 18 to S2                  "); assert_msg_seq_type(18, MSG_APPENDENTRIES_RESPONSE);
    info(41, "S2 receives AER 18 from S1             "); rc_deliver(18, MSG_APPENDENTRIES_RESPONSE);
    info(41, "S2 sends AE|SS 19 to S1                "); assert_msg_seq_type(19, MSG_APPENDENTRIES | MSG_SNAPSHOT);
    info(42, "S2 sends heartbeat                     "); rc_request_timeout(2);
    info(43, "S2 sends AE 20 to S0                   "); assert_msg_seq_type(20, MSG_APPENDENTRIES);
    info(44, "S2 sends AE 21 to S1                   "); assert_msg_seq_type(21, MSG_APPENDENTRIES);
    info(45, "S0 receives RVR 6 from S1              "); rc_deliver(6, MSG_REQUESTVOTE_RESPONSE);
    info(46, "Client appends CMD1 to S2              "); rc_client_operation(2, CMD1);
    info(47, "S1 receives AE 19 from S2              "); rc_deliver(19, MSG_APPENDENTRIES);
    info(47, "S1 sends AER 22 to S2                  "); assert_msg_seq_type(22, MSG_APPENDENTRIES_RESPONSE);
    info(48, "S1 receives AE 21 from S2              "); rc_deliver(21, MSG_APPENDENTRIES);
    info(48, "S1 sends AER 23 to S2                  "); assert_msg_seq_type(23, MSG_APPENDENTRIES_RESPONSE);
    info(49, "S1 executes snapshot                   "); rc_exec_snapshot(1);
    add_to_network_partition(0);
    info(50, "S2 executes snapshot                   "); rc_exec_snapshot(2);
    clear_network_partition();
    info(51, "S2 receives AER 22 from S1             "); rc_deliver(22, MSG_APPENDENTRIES_RESPONSE);
    info(51, "S2 sends AE|SS 24 to S1                "); assert_msg_seq_type(24, MSG_APPENDENTRIES | MSG_SNAPSHOT);
    info(52, "S2 sends heartbeat                     "); rc_request_timeout(2);
    // info(53, "S2 sends AE 25 to S0                   "); assert_msg_seq_type(25, MSG_APPENDENTRIES);
    info(54, "S2 sends AE 26 to S1                   "); assert_msg_seq_type(26, MSG_APPENDENTRIES);
    info(55, "S0 receives unordered AE 25 from S2    "); rc_deliver(25, MSG_NIL);
    // info(55, "S0 sends AER 27 to S2                  "); assert_msg_seq_type(27, MSG_APPENDENTRIES_RESPONSE);
    info(56, "S2 receives unordered AER 27 from S0   "); rc_deliver(27, MSG_APPENDENTRIES_RESPONSE);
    info(57, "S1 receives AE 24 from S2              "); rc_deliver(24, MSG_APPENDENTRIES);
    // info(57, "S1 sends AER 28 to S2                  "); assert_msg_seq_type(28, MSG_APPENDENTRIES_RESPONSE);
    info(58, "S0 receives AE 16 from S2              "); rc_deliver(16, MSG_APPENDENTRIES);
    info(58, "S0 sends AER 29 to S2                  "); assert_msg_seq_type(29, MSG_APPENDENTRIES_RESPONSE);
}

void TestCluster_trace_3_99878_assertion_set_commit_idx_le_current_idx(CuTest * tc) {
#ifdef TEST_CLUSTER_CODE_ASSERTION
    info( 1, "Init 3 servers                         "); rc_init_cluster(3, tc);
    info( 2, "S0 becomes candidate                   "); rc_election_timeout(0);
    info( 3, "S0 sends RV 1 to S1                    "); assert_msg_seq_type(1, MSG_REQUESTVOTE);
    info( 4, "S0 sends RV 2 to S2                    "); assert_msg_seq_type(2, MSG_REQUESTVOTE);
    info( 5, "Network partition add S0               "); add_to_network_partition(0);
    info( 6, "Network not dup unreachable seq 2      ");  
    info( 7, "Network not dup unreachable seq 2      ");  
    info( 8, "S2 becomes candidate                   "); rc_election_timeout(2);
    info( 9, "Network not add unreachable RV S2 -> S0");  
    info(10, "S2 sends RV 3 to S1                    "); assert_msg_seq_type(3, MSG_REQUESTVOTE);
    info(11, "Network partition recovered            "); clear_network_partition();
    info(12, "Network drop seq 2                     "); drop_msg(2);
    info(13, "Network drop seq 3                     "); drop_msg(3);
    info(14, "S1 restarts                            "); rc_restart(1);
    info(15, "S1 receives RV 1 from S0               "); rc_deliver(1, MSG_REQUESTVOTE);
    info(15, "S1 sends RVR 4 to S0                   "); assert_msg_seq_type(4, MSG_REQUESTVOTE_RESPONSE);
    info(16, "S0 receives RVR 4 from S1              "); rc_deliver(4, MSG_REQUESTVOTE_RESPONSE);
    info(17, "S0 sends AE 5 to S1                    "); assert_msg_seq_type(5, MSG_APPENDENTRIES);
    info(18, "S0 sends AE 6 to S2                    "); assert_msg_seq_type(6, MSG_APPENDENTRIES);
    info(19, "Client appends CMD2 to S0              "); rc_client_operation(0, CMD2);
    info(20, "S0 sends AE 7 to S1                    "); assert_msg_seq_type(7, MSG_APPENDENTRIES);
    info(21, "S0 sends AE 8 to S2                    "); assert_msg_seq_type(8, MSG_APPENDENTRIES);
    info(22, "S2 receives unordered AE 8 from S0     "); rc_deliver(8, MSG_APPENDENTRIES);
    info(22, "S2 sends AER 9 to S0                   "); assert_msg_seq_type(9, MSG_APPENDENTRIES_RESPONSE);
    info(23, "Client appends CMD2 to S0              "); rc_client_operation(0, CMD2);
    info(24, "S2 restarts                            "); rc_restart(2);
    info(25, "S1 receives AE 5 from S0               "); rc_deliver(5, MSG_APPENDENTRIES);
    info(25, "S1 sends AER 10 to S0                  "); assert_msg_seq_type(10, MSG_APPENDENTRIES_RESPONSE);
    info(26, "S0 receives AER 9 from S2              "); rc_deliver(9, MSG_APPENDENTRIES_RESPONSE);
    info(26, "S0 sends AE|SS 11 to S2                "); assert_msg_seq_type(11, MSG_APPENDENTRIES | MSG_SNAPSHOT);
    info(27, "S0 executes snapshot                   "); rc_exec_snapshot(0);
    info(28, "Client appends CMD2 to S0              "); rc_client_operation(0, CMD2);
    info(29, "Client appends CMD2 to S0              "); rc_client_operation(0, CMD2);
    info(30, "S0 sends heartbeat                     "); rc_request_timeout(0);
    info(31, "S0 sends AE 12 to S1                   "); assert_msg_seq_type(12, MSG_NIL);
    info(32, "S0 sends AE 13 to S2                   "); assert_msg_seq_type(13, MSG_NIL);
    info(33, "S1 receives unordered AE 12 from S0    "); rc_deliver(12, MSG_NIL);
    info(33, "S1 sends AER 14 to S0                  "); assert_msg_seq_type(14, MSG_NIL);
    info(34, "S1 receives AE 7 from S0               "); rc_deliver(7, MSG_APPENDENTRIES);
    info(34, "S1 sends AER 15 to S0                  "); assert_msg_seq_type(15, MSG_APPENDENTRIES_RESPONSE);
    info(35, "S1 becomes candidate                   "); rc_election_timeout(1);
#endif
}

