#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an RPM
#

# Pull base image
FROM opensuse/leap:42.3
MAINTAINER daos-stack <daos@daos.groups.io>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Add build user (to keep rpmbuild happy)
ENV USER build
RUN useradd -u $UID -ms /bin/bash $USER
RUN groupadd -g $UID $USER

# Install basic tools
RUN zypper --non-interactive up

# basic building
RUN zypper --non-interactive in autoconf automake                        \
                                ca-certificates-mozilla curl createrepo  \
                                git libtool lsb-release make             \
                                perl-libwww-perl perl-LWP-Protocol-https \
                                perl-XML-Parser rpm-build sudo

# need to run the build command as root, as it needs to chroot
RUN if ! grep "^#includedir /etc/sudoers.d" /etc/sudoers; then              \
        echo "#includedir /etc/sudoers.d" >> /etc/sudoers;                  \
    fi;                                                                     \
    echo "build ALL=(ALL) NOPASSWD: /usr/bin/build" > /etc/sudoers.d/build; \
    echo "build ALL=(ALL) NOPASSWD: /bin/rpm" >> /etc/sudoers.d/build;      \
    chmod 0440 /etc/sudoers.d/build;                                        \
    visudo -c;                                                              \
    sudo -l -U build

ENV OPENSUSE_REPO="https://download.opensuse.org/repositories"
ENV TOOLS="${OPENSUSE_REPO}/openSUSE:Tools/openSUSE_42.3/openSUSE:Tools.repo"

RUN set -x; zypper --non-interactive ar ${TOOLS}; \
    zypper --non-interactive --gpg-auto-import-keys ref \
      'openSUSE.org tools (openSUSE_42.3)'

RUN zypper --non-interactive in build
